// vocab.js
// Expanded Senderos-style vocabulary for Lingo Día.
// This is organized by common Spanish 1, 2, and 3 themes; it is not copied from a textbook.

const words = [
  {
    spanish: "me llamo",
    english: "my name is",
    pos: "phrase",
    example: "Me llamo Sofía.",
    translation: "My name is Sofía.",
    tip: "Use me llamo to introduce yourself.",
    category: "Greetings & Introductions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "te presento a",
    english: "let me introduce you to",
    pos: "phrase",
    example: "Te presento a mi amigo Carlos.",
    translation: "Let me introduce you to my friend Carlos.",
    tip: "Presento comes from presentar.",
    category: "Greetings & Introductions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "encantado",
    english: "pleased to meet you",
    pos: "adjective",
    example: "Encantado de conocerte.",
    translation: "Pleased to meet you.",
    tip: "Use encantado/encantada depending on speaker.",
    category: "Greetings & Introductions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "mucho gusto",
    english: "nice to meet you",
    pos: "phrase",
    example: "Mucho gusto, señor García.",
    translation: "Nice to meet you, Mr. García.",
    tip: "A standard polite introduction.",
    category: "Greetings & Introductions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "¿Qué tal?",
    english: "How’s it going?",
    pos: "phrase",
    example: "Hola, ¿qué tal?",
    translation: "Hi, how’s it going?",
    tip: "Casual greeting question.",
    category: "Greetings & Introductions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "hasta luego",
    english: "see you later",
    pos: "phrase",
    example: "Tengo que irme. Hasta luego.",
    translation: "I have to go. See you later.",
    tip: "Hasta means until.",
    category: "Greetings & Introductions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "nos vemos",
    english: "see you",
    pos: "phrase",
    example: "Nos vemos mañana.",
    translation: "See you tomorrow.",
    tip: "Literally, we will see each other.",
    category: "Greetings & Introductions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "de nada",
    english: "you’re welcome",
    pos: "phrase",
    example: "Gracias. De nada.",
    translation: "Thank you. You’re welcome.",
    tip: "Use after someone says gracias.",
    category: "Greetings & Introductions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el cuaderno",
    english: "notebook",
    pos: "noun",
    example: "Escribo en mi cuaderno.",
    translation: "I write in my notebook.",
    tip: "Cuaderno means notebook.",
    category: "Classroom",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el lápiz",
    english: "pencil",
    pos: "noun",
    example: "Necesito un lápiz.",
    translation: "I need a pencil.",
    tip: "Lápiz has an accent.",
    category: "Classroom",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la mochila",
    english: "backpack",
    pos: "noun",
    example: "Mi mochila es pesada.",
    translation: "My backpack is heavy.",
    tip: "Mochila means backpack.",
    category: "Classroom",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la pizarra",
    english: "board",
    pos: "noun",
    example: "La profesora escribe en la pizarra.",
    translation: "The teacher writes on the board.",
    tip: "Pizarra means classroom board.",
    category: "Classroom",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el escritorio",
    english: "desk",
    pos: "noun",
    example: "El libro está en el escritorio.",
    translation: "The book is on the desk.",
    tip: "Escritorio means desk.",
    category: "Classroom",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la silla",
    english: "chair",
    pos: "noun",
    example: "La silla está al lado de la mesa.",
    translation: "The chair is next to the table.",
    tip: "Silla means chair.",
    category: "Classroom",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la calculadora",
    english: "calculator",
    pos: "noun",
    example: "Uso la calculadora en la clase de matemáticas.",
    translation: "I use the calculator in math class.",
    tip: "Calculadora looks like calculator.",
    category: "Classroom",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la carpeta",
    english: "folder / binder",
    pos: "noun",
    example: "Pongo los papeles en la carpeta.",
    translation: "I put the papers in the folder.",
    tip: "Carpeta means folder, not carpet.",
    category: "Classroom",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la tarea",
    english: "homework",
    pos: "noun",
    example: "Tengo mucha tarea hoy.",
    translation: "I have a lot of homework today.",
    tip: "Tarea is a very common school word.",
    category: "School Life",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el examen",
    english: "test",
    pos: "noun",
    example: "El examen es difícil.",
    translation: "The test is difficult.",
    tip: "Examen looks like exam.",
    category: "School Life",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la clase",
    english: "class",
    pos: "noun",
    example: "La clase de español es interesante.",
    translation: "Spanish class is interesting.",
    tip: "Clase looks like class.",
    category: "School Life",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el horario",
    english: "schedule",
    pos: "noun",
    example: "Mi horario es ocupado.",
    translation: "My schedule is busy.",
    tip: "Horario means schedule/timetable.",
    category: "School Life",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "sacar una buena nota",
    english: "to get a good grade",
    pos: "phrase",
    example: "Quiero sacar una buena nota.",
    translation: "I want to get a good grade.",
    tip: "Sacar can mean to get/earn in school.",
    category: "School Life",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "prestar atención",
    english: "to pay attention",
    pos: "phrase",
    example: "Necesito prestar atención en clase.",
    translation: "I need to pay attention in class.",
    tip: "Prestar atención means pay attention.",
    category: "School Life",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "entregar",
    english: "to turn in",
    pos: "verb",
    example: "Tengo que entregar el proyecto mañana.",
    translation: "I have to turn in the project tomorrow.",
    tip: "Entregar means to hand in/turn in.",
    category: "School Life",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "llegar tarde",
    english: "to arrive late",
    pos: "phrase",
    example: "No quiero llegar tarde a clase.",
    translation: "I do not want to arrive late to class.",
    tip: "Llegar means to arrive.",
    category: "School Life",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la hora",
    english: "hour / time",
    pos: "noun",
    example: "¿Qué hora es?",
    translation: "What time is it?",
    tip: "Hora is used when asking time.",
    category: "Numbers & Time",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "temprano",
    english: "early",
    pos: "adverb",
    example: "Llego temprano a la escuela.",
    translation: "I arrive early to school.",
    tip: "Temprano means early.",
    category: "Numbers & Time",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "tarde",
    english: "late / afternoon",
    pos: "adverb/noun",
    example: "Llego tarde a clase.",
    translation: "I arrive late to class.",
    tip: "Tarde can mean late or afternoon.",
    category: "Numbers & Time",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "medianoche",
    english: "midnight",
    pos: "noun",
    example: "Estudio hasta medianoche.",
    translation: "I study until midnight.",
    tip: "Media + noche = middle of night.",
    category: "Numbers & Time",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "mediodía",
    english: "noon",
    pos: "noun",
    example: "Almuerzo al mediodía.",
    translation: "I eat lunch at noon.",
    tip: "Medio + día = middle of day.",
    category: "Numbers & Time",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el minuto",
    english: "minute",
    pos: "noun",
    example: "Tengo cinco minutos.",
    translation: "I have five minutes.",
    tip: "Minuto looks like minute.",
    category: "Numbers & Time",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el reloj",
    english: "clock / watch",
    pos: "noun",
    example: "Miro el reloj.",
    translation: "I look at the clock.",
    tip: "Reloj means clock or watch.",
    category: "Numbers & Time",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "a tiempo",
    english: "on time",
    pos: "phrase",
    example: "Llego a tiempo.",
    translation: "I arrive on time.",
    tip: "A tiempo means on time.",
    category: "Numbers & Time",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "hace frío",
    english: "it is cold",
    pos: "phrase",
    example: "Hoy hace frío.",
    translation: "Today it is cold.",
    tip: "Spanish often uses hace for weather.",
    category: "Calendar & Weather",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "hace calor",
    english: "it is hot",
    pos: "phrase",
    example: "En julio hace calor.",
    translation: "In July it is hot.",
    tip: "Hace calor means it is hot.",
    category: "Calendar & Weather",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "llueve",
    english: "it rains / it is raining",
    pos: "verb",
    example: "Llueve mucho en abril.",
    translation: "It rains a lot in April.",
    tip: "Llueve comes from llover.",
    category: "Calendar & Weather",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "nieva",
    english: "it snows / it is snowing",
    pos: "verb",
    example: "Nieva en invierno.",
    translation: "It snows in winter.",
    tip: "Nieva comes from nevar.",
    category: "Calendar & Weather",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "está nublado",
    english: "it is cloudy",
    pos: "phrase",
    example: "Hoy está nublado.",
    translation: "Today it is cloudy.",
    tip: "Nublado means cloudy.",
    category: "Calendar & Weather",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la primavera",
    english: "spring",
    pos: "noun",
    example: "La primavera es bonita.",
    translation: "Spring is pretty.",
    tip: "Primavera means spring.",
    category: "Calendar & Weather",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el verano",
    english: "summer",
    pos: "noun",
    example: "En el verano no hay escuela.",
    translation: "In the summer there is no school.",
    tip: "Verano means summer.",
    category: "Calendar & Weather",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el invierno",
    english: "winter",
    pos: "noun",
    example: "Hace frío en el invierno.",
    translation: "It is cold in the winter.",
    tip: "Invierno means winter.",
    category: "Calendar & Weather",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la familia",
    english: "family",
    pos: "noun",
    example: "Mi familia es grande.",
    translation: "My family is big.",
    tip: "Familia looks like family.",
    category: "Family",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el hermano",
    english: "brother",
    pos: "noun",
    example: "Mi hermano es simpático.",
    translation: "My brother is nice.",
    tip: "Hermano means brother.",
    category: "Family",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la hermana",
    english: "sister",
    pos: "noun",
    example: "Mi hermana estudia mucho.",
    translation: "My sister studies a lot.",
    tip: "Hermana means sister.",
    category: "Family",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "los abuelos",
    english: "grandparents",
    pos: "noun",
    example: "Mis abuelos viven cerca.",
    translation: "My grandparents live nearby.",
    tip: "Abuelos can mean grandparents.",
    category: "Family",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el primo",
    english: "cousin",
    pos: "noun",
    example: "Mi primo juega al fútbol.",
    translation: "My cousin plays soccer.",
    tip: "Primo means cousin.",
    category: "Family",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la tía",
    english: "aunt",
    pos: "noun",
    example: "Mi tía vive en Chicago.",
    translation: "My aunt lives in Chicago.",
    tip: "Tía means aunt.",
    category: "Family",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el tío",
    english: "uncle",
    pos: "noun",
    example: "Mi tío cocina muy bien.",
    translation: "My uncle cooks very well.",
    tip: "Tío means uncle.",
    category: "Family",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "menor",
    english: "younger",
    pos: "adjective",
    example: "Mi hermana menor tiene diez años.",
    translation: "My younger sister is ten years old.",
    tip: "Menor means younger/smaller.",
    category: "Family",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "simpático",
    english: "nice",
    pos: "adjective",
    example: "Mi amigo es simpático.",
    translation: "My friend is nice.",
    tip: "Use simpático/a depending on gender.",
    category: "Descriptions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "trabajador",
    english: "hardworking",
    pos: "adjective",
    example: "Ella es trabajadora.",
    translation: "She is hardworking.",
    tip: "Comes from trabajar.",
    category: "Descriptions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "perezoso",
    english: "lazy",
    pos: "adjective",
    example: "El gato es perezoso.",
    translation: "The cat is lazy.",
    tip: "Use carefully; it describes laziness.",
    category: "Descriptions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "atrevido",
    english: "daring",
    pos: "adjective",
    example: "Mi primo es atrevido.",
    translation: "My cousin is daring.",
    tip: "Atrevido means bold/daring.",
    category: "Descriptions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "gracioso",
    english: "funny",
    pos: "adjective",
    example: "El video es gracioso.",
    translation: "The video is funny.",
    tip: "Gracioso can mean funny.",
    category: "Descriptions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "inteligente",
    english: "intelligent",
    pos: "adjective",
    example: "La estudiante es inteligente.",
    translation: "The student is intelligent.",
    tip: "Same form for masculine/feminine.",
    category: "Descriptions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "ordenado",
    english: "organized / tidy",
    pos: "adjective",
    example: "Mi cuarto está ordenado.",
    translation: "My room is tidy.",
    tip: "Ordenado means organized/tidy.",
    category: "Descriptions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "moreno",
    english: "dark-haired / dark-skinned",
    pos: "adjective",
    example: "Mi amigo es moreno.",
    translation: "My friend is dark-haired/dark-skinned.",
    tip: "Description word; use respectfully.",
    category: "Descriptions",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el desayuno",
    english: "breakfast",
    pos: "noun",
    example: "Como fruta para el desayuno.",
    translation: "I eat fruit for breakfast.",
    tip: "Desayuno means breakfast.",
    category: "Food & Meals",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el almuerzo",
    english: "lunch",
    pos: "noun",
    example: "El almuerzo es a las doce.",
    translation: "Lunch is at twelve.",
    tip: "Almuerzo means lunch.",
    category: "Food & Meals",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la cena",
    english: "dinner",
    pos: "noun",
    example: "La cena está lista.",
    translation: "Dinner is ready.",
    tip: "Cena means dinner.",
    category: "Food & Meals",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "tener hambre",
    english: "to be hungry",
    pos: "phrase",
    example: "Tengo hambre después de clase.",
    translation: "I am hungry after class.",
    tip: "Spanish says to have hunger.",
    category: "Food & Meals",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "tener sed",
    english: "to be thirsty",
    pos: "phrase",
    example: "Tengo sed después de correr.",
    translation: "I am thirsty after running.",
    tip: "Spanish says to have thirst.",
    category: "Food & Meals",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "pedir",
    english: "to order / ask for",
    pos: "verb",
    example: "Quiero pedir una ensalada.",
    translation: "I want to order a salad.",
    tip: "Pedir is often used in restaurants.",
    category: "Food & Meals",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la cuenta",
    english: "bill / check",
    pos: "noun",
    example: "Necesitamos la cuenta, por favor.",
    translation: "We need the check, please.",
    tip: "Cuenta can mean bill/account.",
    category: "Food & Meals",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el postre",
    english: "dessert",
    pos: "noun",
    example: "Quiero postre después de la cena.",
    translation: "I want dessert after dinner.",
    tip: "Postre means dessert.",
    category: "Food & Meals",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "escuchar música",
    english: "to listen to music",
    pos: "phrase",
    example: "Me gusta escuchar música.",
    translation: "I like to listen to music.",
    tip: "Escuchar means to listen.",
    category: "Leisure Activities",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "jugar videojuegos",
    english: "to play video games",
    pos: "phrase",
    example: "Quiero jugar videojuegos.",
    translation: "I want to play video games.",
    tip: "Jugar is used with games/sports.",
    category: "Leisure Activities",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "pasar tiempo con amigos",
    english: "to spend time with friends",
    pos: "phrase",
    example: "Me gusta pasar tiempo con amigos.",
    translation: "I like to spend time with friends.",
    tip: "Pasar tiempo means spend time.",
    category: "Leisure Activities",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "practicar deportes",
    english: "to play/practice sports",
    pos: "phrase",
    example: "Practico deportes los sábados.",
    translation: "I play sports on Saturdays.",
    tip: "Practicar is common for sports and skills.",
    category: "Leisure Activities",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "ir de compras",
    english: "to go shopping",
    pos: "phrase",
    example: "Voy de compras con mi madre.",
    translation: "I go shopping with my mother.",
    tip: "Ir de compras means go shopping.",
    category: "Leisure Activities",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "ver películas",
    english: "to watch movies",
    pos: "phrase",
    example: "Me gusta ver películas.",
    translation: "I like to watch movies.",
    tip: "Ver means to watch/see.",
    category: "Leisure Activities",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "leer novelas",
    english: "to read novels",
    pos: "phrase",
    example: "Me gusta leer novelas.",
    translation: "I like to read novels.",
    tip: "Leer means to read.",
    category: "Leisure Activities",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "tocar la guitarra",
    english: "to play the guitar",
    pos: "phrase",
    example: "Mi amigo toca la guitarra.",
    translation: "My friend plays the guitar.",
    tip: "Tocar is used for instruments.",
    category: "Leisure Activities",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la biblioteca",
    english: "library",
    pos: "noun",
    example: "Estudio en la biblioteca.",
    translation: "I study in the library.",
    tip: "Biblioteca means library, not bookstore.",
    category: "Places",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el gimnasio",
    english: "gym",
    pos: "noun",
    example: "Tenemos práctica en el gimnasio.",
    translation: "We have practice in the gym.",
    tip: "Gimnasio means gym.",
    category: "Places",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la cafetería",
    english: "cafeteria",
    pos: "noun",
    example: "Almuerzo en la cafetería.",
    translation: "I eat lunch in the cafeteria.",
    tip: "Cafetería looks like cafeteria.",
    category: "Places",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el parque",
    english: "park",
    pos: "noun",
    example: "Camino en el parque.",
    translation: "I walk in the park.",
    tip: "Parque means park.",
    category: "Places",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la tienda",
    english: "store",
    pos: "noun",
    example: "Voy a la tienda después de clase.",
    translation: "I go to the store after class.",
    tip: "Tienda means store.",
    category: "Places",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el restaurante",
    english: "restaurant",
    pos: "noun",
    example: "Comemos en el restaurante.",
    translation: "We eat at the restaurant.",
    tip: "Restaurante looks like restaurant.",
    category: "Places",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el cine",
    english: "movie theater",
    pos: "noun",
    example: "Voy al cine los viernes.",
    translation: "I go to the movies on Fridays.",
    tip: "Cine means movie theater/cinema.",
    category: "Places",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la iglesia",
    english: "church",
    pos: "noun",
    example: "La iglesia está cerca del parque.",
    translation: "The church is near the park.",
    tip: "Iglesia means church.",
    category: "Places",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la casa",
    english: "house",
    pos: "noun",
    example: "Mi casa es pequeña.",
    translation: "My house is small.",
    tip: "Casa means house.",
    category: "House & Rooms",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el cuarto",
    english: "room / bedroom",
    pos: "noun",
    example: "Mi cuarto está limpio.",
    translation: "My room is clean.",
    tip: "Cuarto often means bedroom.",
    category: "House & Rooms",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la cocina",
    english: "kitchen",
    pos: "noun",
    example: "Mi madre está en la cocina.",
    translation: "My mother is in the kitchen.",
    tip: "Cocina means kitchen.",
    category: "House & Rooms",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "el baño",
    english: "bathroom",
    pos: "noun",
    example: "El baño está al lado del cuarto.",
    translation: "The bathroom is next to the room.",
    tip: "Baño means bathroom.",
    category: "House & Rooms",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la sala",
    english: "living room",
    pos: "noun",
    example: "Vemos televisión en la sala.",
    translation: "We watch TV in the living room.",
    tip: "Sala means living room.",
    category: "House & Rooms",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la cama",
    english: "bed",
    pos: "noun",
    example: "La cama es cómoda.",
    translation: "The bed is comfortable.",
    tip: "Cama means bed.",
    category: "House & Rooms",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la mesa",
    english: "table",
    pos: "noun",
    example: "La comida está en la mesa.",
    translation: "The food is on the table.",
    tip: "Mesa means table.",
    category: "House & Rooms",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "la puerta",
    english: "door",
    pos: "noun",
    example: "Cierra la puerta, por favor.",
    translation: "Close the door, please.",
    tip: "Puerta means door.",
    category: "House & Rooms",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "aprender",
    english: "to learn",
    pos: "verb",
    example: "Quiero aprender español.",
    translation: "I want to learn Spanish.",
    tip: "Aprender means to learn.",
    category: "Present Tense Verbs",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "estudiar",
    english: "to study",
    pos: "verb",
    example: "Estudio todos los días.",
    translation: "I study every day.",
    tip: "Estudiar looks like study.",
    category: "Present Tense Verbs",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "escribir",
    english: "to write",
    pos: "verb",
    example: "Escribo en mi cuaderno.",
    translation: "I write in my notebook.",
    tip: "Escribir means to write.",
    category: "Present Tense Verbs",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "vivir",
    english: "to live",
    pos: "verb",
    example: "Vivo en Illinois.",
    translation: "I live in Illinois.",
    tip: "Vivir means to live.",
    category: "Present Tense Verbs",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "compartir",
    english: "to share",
    pos: "verb",
    example: "Comparto mis apuntes.",
    translation: "I share my notes.",
    tip: "Compartir means to share.",
    category: "Present Tense Verbs",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "necesitar",
    english: "to need",
    pos: "verb",
    example: "Necesito ayuda.",
    translation: "I need help.",
    tip: "Necesitar means to need.",
    category: "Present Tense Verbs",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "querer",
    english: "to want / love",
    pos: "verb",
    example: "Quiero una buena nota.",
    translation: "I want a good grade.",
    tip: "Querer can mean want or love.",
    category: "Present Tense Verbs",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "preferir",
    english: "to prefer",
    pos: "verb",
    example: "Prefiero estudiar por la mañana.",
    translation: "I prefer to study in the morning.",
    tip: "Preferir is a stem-changing verb.",
    category: "Present Tense Verbs",
    level: "Senderos 1",
    dailyEligible: true
  },
  {
    spanish: "fui",
    english: "I went / I was",
    pos: "verb",
    example: "Fui al cine anoche.",
    translation: "I went to the movies last night.",
    tip: "Fui can be from ir or ser in the preterite.",
    category: "Preterite",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "hice",
    english: "I did / I made",
    pos: "verb",
    example: "Hice la tarea.",
    translation: "I did the homework.",
    tip: "Hice is the yo preterite of hacer.",
    category: "Preterite",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "tuve",
    english: "I had",
    pos: "verb",
    example: "Tuve un examen.",
    translation: "I had a test.",
    tip: "Tuve is the yo preterite of tener.",
    category: "Preterite",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "pude",
    english: "I was able to",
    pos: "verb",
    example: "Pude terminar el proyecto.",
    translation: "I was able to finish the project.",
    tip: "Pude is the yo preterite of poder.",
    category: "Preterite",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "dije",
    english: "I said / told",
    pos: "verb",
    example: "Dije la verdad.",
    translation: "I told the truth.",
    tip: "Dije is the yo preterite of decir.",
    category: "Preterite",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "traje",
    english: "I brought",
    pos: "verb",
    example: "Traje mi libro a clase.",
    translation: "I brought my book to class.",
    tip: "Traje is the yo preterite of traer.",
    category: "Preterite",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "estuve",
    english: "I was",
    pos: "verb",
    example: "Estuve en casa ayer.",
    translation: "I was at home yesterday.",
    tip: "Estuve is preterite of estar.",
    category: "Preterite",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "empecé",
    english: "I began",
    pos: "verb",
    example: "Empecé la tarea temprano.",
    translation: "I began the homework early.",
    tip: "Empecé changes spelling to keep the sound.",
    category: "Preterite",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "era",
    english: "I/he/she was",
    pos: "verb",
    example: "Cuando era niña, leía mucho.",
    translation: "When I was a child, I read a lot.",
    tip: "Era describes ongoing/background traits in the past.",
    category: "Imperfect",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "iba",
    english: "I/he/she used to go",
    pos: "verb",
    example: "Iba a la biblioteca después de clase.",
    translation: "I used to go to the library after class.",
    tip: "Iba is imperfect of ir.",
    category: "Imperfect",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "tenía",
    english: "I/he/she had",
    pos: "verb",
    example: "Tenía mucha energía.",
    translation: "I had a lot of energy.",
    tip: "Tenía is imperfect of tener.",
    category: "Imperfect",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "mientras",
    english: "while",
    pos: "conjunction",
    example: "Escuchaba música mientras estudiaba.",
    translation: "I listened to music while I studied.",
    tip: "Mientras often connects simultaneous past actions.",
    category: "Imperfect",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "siempre",
    english: "always",
    pos: "adverb",
    example: "Siempre jugaba afuera.",
    translation: "I always played outside.",
    tip: "Siempre is common with repeated past actions.",
    category: "Imperfect",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "a menudo",
    english: "often",
    pos: "adverb",
    example: "A menudo visitábamos a mis abuelos.",
    translation: "We often visited my grandparents.",
    tip: "A menudo means often.",
    category: "Imperfect",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "de vez en cuando",
    english: "once in a while",
    pos: "phrase",
    example: "De vez en cuando veía películas.",
    translation: "Once in a while I watched movies.",
    tip: "Useful for habitual past actions.",
    category: "Imperfect",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "todos los veranos",
    english: "every summer",
    pos: "phrase",
    example: "Todos los veranos viajábamos.",
    translation: "Every summer we traveled.",
    tip: "Repeated time phrase for imperfect.",
    category: "Imperfect",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "de niño",
    english: "as a child",
    pos: "phrase",
    example: "De niño, jugaba afuera.",
    translation: "As a child, I played outside.",
    tip: "Change niño/niña depending on speaker.",
    category: "Childhood",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "los juguetes",
    english: "toys",
    pos: "noun",
    example: "Tenía muchos juguetes.",
    translation: "I had many toys.",
    tip: "Juguetes are toys.",
    category: "Childhood",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la muñeca",
    english: "doll",
    pos: "noun",
    example: "Mi hermana tenía una muñeca.",
    translation: "My sister had a doll.",
    tip: "Muñeca can mean doll or wrist.",
    category: "Childhood",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el oso de peluche",
    english: "teddy bear",
    pos: "noun",
    example: "Dormía con un oso de peluche.",
    translation: "I slept with a teddy bear.",
    tip: "Peluche means plush/stuffed toy.",
    category: "Childhood",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el patio de recreo",
    english: "playground",
    pos: "noun",
    example: "Jugábamos en el patio de recreo.",
    translation: "We played on the playground.",
    tip: "Recreo can mean recess/playtime.",
    category: "Childhood",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "obediente",
    english: "obedient",
    pos: "adjective",
    example: "Era una niña obediente.",
    translation: "I was an obedient child.",
    tip: "Common childhood description.",
    category: "Childhood",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "travieso",
    english: "mischievous",
    pos: "adjective",
    example: "Mi hermano era travieso.",
    translation: "My brother was mischievous.",
    tip: "Travieso means mischievous.",
    category: "Childhood",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "coleccionar",
    english: "to collect",
    pos: "verb",
    example: "Coleccionaba tarjetas.",
    translation: "I collected cards.",
    tip: "Coleccionar looks like collect.",
    category: "Childhood",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el viaje",
    english: "trip",
    pos: "noun",
    example: "El viaje fue divertido.",
    translation: "The trip was fun.",
    tip: "Viaje is a trip; viajar is to travel.",
    category: "Travel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "viajar",
    english: "to travel",
    pos: "verb",
    example: "Quiero viajar a Perú.",
    translation: "I want to travel to Peru.",
    tip: "Viajar means to travel.",
    category: "Travel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la excursión",
    english: "excursion / field trip",
    pos: "noun",
    example: "La excursión fue interesante.",
    translation: "The field trip was interesting.",
    tip: "Excursión looks like excursion.",
    category: "Travel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el itinerario",
    english: "itinerary",
    pos: "noun",
    example: "El itinerario incluye tres museos.",
    translation: "The itinerary includes three museums.",
    tip: "Itinerario looks like itinerary.",
    category: "Travel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "hacer las maletas",
    english: "to pack",
    pos: "phrase",
    example: "Tengo que hacer las maletas.",
    translation: "I have to pack.",
    tip: "Literally means to make the suitcases.",
    category: "Travel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el destino",
    english: "destination",
    pos: "noun",
    example: "Nuestro destino es Madrid.",
    translation: "Our destination is Madrid.",
    tip: "Destino means destination.",
    category: "Travel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el recuerdo",
    english: "souvenir / memory",
    pos: "noun",
    example: "Compré un recuerdo en México.",
    translation: "I bought a souvenir in Mexico.",
    tip: "Recuerdo can mean memory or souvenir.",
    category: "Travel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el guía turístico",
    english: "tour guide",
    pos: "noun",
    example: "El guía turístico explicó la historia.",
    translation: "The tour guide explained the history.",
    tip: "Guía turístico means tour guide.",
    category: "Travel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el aeropuerto",
    english: "airport",
    pos: "noun",
    example: "Llegamos al aeropuerto temprano.",
    translation: "We arrived at the airport early.",
    tip: "Aero connects to air.",
    category: "Airport & Hotel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el pasaporte",
    english: "passport",
    pos: "noun",
    example: "Necesito mi pasaporte para viajar.",
    translation: "I need my passport to travel.",
    tip: "Pasaporte looks like passport.",
    category: "Airport & Hotel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el boleto",
    english: "ticket",
    pos: "noun",
    example: "Compré un boleto para el tren.",
    translation: "I bought a ticket for the train.",
    tip: "Boleto means ticket.",
    category: "Airport & Hotel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la habitación",
    english: "hotel room / bedroom",
    pos: "noun",
    example: "La habitación está limpia.",
    translation: "The room is clean.",
    tip: "Habitación can mean room/bedroom.",
    category: "Airport & Hotel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la recepción",
    english: "front desk / reception",
    pos: "noun",
    example: "Hablé con la persona en la recepción.",
    translation: "I talked to the person at the front desk.",
    tip: "Recepción looks like reception.",
    category: "Airport & Hotel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la llave",
    english: "key",
    pos: "noun",
    example: "Perdí la llave de la habitación.",
    translation: "I lost the room key.",
    tip: "Llave means key.",
    category: "Airport & Hotel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la tarjeta de embarque",
    english: "boarding pass",
    pos: "noun",
    example: "Necesito mi tarjeta de embarque.",
    translation: "I need my boarding pass.",
    tip: "Embarque relates to boarding.",
    category: "Airport & Hotel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "facturar el equipaje",
    english: "to check luggage",
    pos: "phrase",
    example: "Vamos a facturar el equipaje.",
    translation: "We are going to check the luggage.",
    tip: "Equipaje means luggage.",
    category: "Airport & Hotel",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la esquina",
    english: "corner",
    pos: "noun",
    example: "La tienda está en la esquina.",
    translation: "The store is on the corner.",
    tip: "Esquina means corner.",
    category: "City & Directions",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "derecho",
    english: "straight ahead",
    pos: "adverb",
    example: "Sigue derecho por dos cuadras.",
    translation: "Go straight for two blocks.",
    tip: "Derecho can mean straight/right/law depending context.",
    category: "City & Directions",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "doblar",
    english: "to turn",
    pos: "verb",
    example: "Dobla a la izquierda.",
    translation: "Turn left.",
    tip: "Doblar means to turn/fold.",
    category: "City & Directions",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la cuadra",
    english: "block",
    pos: "noun",
    example: "Camina tres cuadras.",
    translation: "Walk three blocks.",
    tip: "Cuadra means city block.",
    category: "City & Directions",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el semáforo",
    english: "traffic light",
    pos: "noun",
    example: "Dobla en el semáforo.",
    translation: "Turn at the traffic light.",
    tip: "Semáforo means traffic light.",
    category: "City & Directions",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "cruzar",
    english: "to cross",
    pos: "verb",
    example: "Cruza la calle con cuidado.",
    translation: "Cross the street carefully.",
    tip: "Cruzar means to cross.",
    category: "City & Directions",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la avenida",
    english: "avenue",
    pos: "noun",
    example: "La escuela está en la avenida principal.",
    translation: "The school is on the main avenue.",
    tip: "Avenida means avenue.",
    category: "City & Directions",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "perderse",
    english: "to get lost",
    pos: "verb",
    example: "No quiero perderme en la ciudad.",
    translation: "I do not want to get lost in the city.",
    tip: "Reflexive verb: perderse.",
    category: "City & Directions",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "me duele",
    english: "my ___ hurts",
    pos: "phrase",
    example: "Me duele la cabeza.",
    translation: "My head hurts.",
    tip: "Use me duele with singular body parts.",
    category: "Health & Body",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la garganta",
    english: "throat",
    pos: "noun",
    example: "Me duele la garganta.",
    translation: "My throat hurts.",
    tip: "Garganta means throat.",
    category: "Health & Body",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la fiebre",
    english: "fever",
    pos: "noun",
    example: "Tengo fiebre.",
    translation: "I have a fever.",
    tip: "Fiebre means fever.",
    category: "Health & Body",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la receta",
    english: "prescription / recipe",
    pos: "noun",
    example: "El médico escribió una receta.",
    translation: "The doctor wrote a prescription.",
    tip: "Receta can mean recipe or prescription.",
    category: "Health & Body",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la tos",
    english: "cough",
    pos: "noun",
    example: "Tengo tos desde ayer.",
    translation: "I have had a cough since yesterday.",
    tip: "Tos means cough.",
    category: "Health & Body",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "estornudar",
    english: "to sneeze",
    pos: "verb",
    example: "Estornudo mucho en la primavera.",
    translation: "I sneeze a lot in spring.",
    tip: "Estornudar means to sneeze.",
    category: "Health & Body",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el consultorio",
    english: "doctor’s office",
    pos: "noun",
    example: "Voy al consultorio médico.",
    translation: "I am going to the doctor’s office.",
    tip: "Consultorio is an office/clinic.",
    category: "Health & Body",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "descansar",
    english: "to rest",
    pos: "verb",
    example: "Debes descansar si estás enfermo.",
    translation: "You should rest if you are sick.",
    tip: "Descansar means to rest.",
    category: "Health & Body",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "barrer",
    english: "to sweep",
    pos: "verb",
    example: "Tengo que barrer el piso.",
    translation: "I have to sweep the floor.",
    tip: "Barrer is a chore verb.",
    category: "Chores",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "lavar los platos",
    english: "to wash the dishes",
    pos: "phrase",
    example: "Voy a lavar los platos.",
    translation: "I am going to wash the dishes.",
    tip: "Lavar means to wash.",
    category: "Chores",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "sacar la basura",
    english: "to take out the trash",
    pos: "phrase",
    example: "Tengo que sacar la basura.",
    translation: "I have to take out the trash.",
    tip: "Sacar means to take out.",
    category: "Chores",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "arreglar el cuarto",
    english: "to straighten up the room",
    pos: "phrase",
    example: "Debo arreglar mi cuarto.",
    translation: "I should straighten up my room.",
    tip: "Arreglar means to fix/arrange.",
    category: "Chores",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "pasar la aspiradora",
    english: "to vacuum",
    pos: "phrase",
    example: "Paso la aspiradora los sábados.",
    translation: "I vacuum on Saturdays.",
    tip: "Aspiradora means vacuum.",
    category: "Chores",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "quitar el polvo",
    english: "to dust",
    pos: "phrase",
    example: "Voy a quitar el polvo de la mesa.",
    translation: "I am going to dust the table.",
    tip: "Literally remove the dust.",
    category: "Chores",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "cortar el césped",
    english: "to mow the lawn",
    pos: "phrase",
    example: "Mi hermano corta el césped.",
    translation: "My brother mows the lawn.",
    tip: "Césped means lawn/grass.",
    category: "Chores",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "hacer la cama",
    english: "to make the bed",
    pos: "phrase",
    example: "Hago la cama por la mañana.",
    translation: "I make the bed in the morning.",
    tip: "Common household phrase.",
    category: "Chores",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la talla",
    english: "size",
    pos: "noun",
    example: "Necesito una talla más grande.",
    translation: "I need a bigger size.",
    tip: "Talla means clothing size.",
    category: "Shopping",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "probarse",
    english: "to try on",
    pos: "verb",
    example: "Quiero probarme los zapatos.",
    translation: "I want to try on the shoes.",
    tip: "Reflexive verb for trying clothes on.",
    category: "Shopping",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la caja",
    english: "cash register / box",
    pos: "noun",
    example: "Pago en la caja.",
    translation: "I pay at the register.",
    tip: "Caja can mean box or register.",
    category: "Shopping",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "barato",
    english: "cheap",
    pos: "adjective",
    example: "La camisa es barata.",
    translation: "The shirt is cheap.",
    tip: "Barato/a means cheap/inexpensive.",
    category: "Shopping",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "caro",
    english: "expensive",
    pos: "adjective",
    example: "El abrigo es caro.",
    translation: "The coat is expensive.",
    tip: "Caro/a means expensive.",
    category: "Shopping",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "en oferta",
    english: "on sale",
    pos: "phrase",
    example: "Los zapatos están en oferta.",
    translation: "The shoes are on sale.",
    tip: "Oferta means sale/offer.",
    category: "Shopping",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "devolver",
    english: "to return",
    pos: "verb",
    example: "Quiero devolver esta falda.",
    translation: "I want to return this skirt.",
    tip: "Devolver means return/give back.",
    category: "Shopping",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el recibo",
    english: "receipt",
    pos: "noun",
    example: "Necesito el recibo.",
    translation: "I need the receipt.",
    tip: "Recibo means receipt.",
    category: "Shopping",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el mesero",
    english: "waiter",
    pos: "noun",
    example: "El mesero trae el menú.",
    translation: "The waiter brings the menu.",
    tip: "Mesero means waiter.",
    category: "Restaurants",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la propina",
    english: "tip",
    pos: "noun",
    example: "Dejamos una propina.",
    translation: "We left a tip.",
    tip: "Propina means tip.",
    category: "Restaurants",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el plato principal",
    english: "main dish",
    pos: "noun",
    example: "El plato principal es pollo.",
    translation: "The main dish is chicken.",
    tip: "Plato principal means main course.",
    category: "Restaurants",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la entrada",
    english: "appetizer / entrance",
    pos: "noun",
    example: "Pedimos una entrada.",
    translation: "We ordered an appetizer.",
    tip: "Entrada can mean entrance or appetizer.",
    category: "Restaurants",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "pedir",
    english: "to order",
    pos: "verb",
    example: "Voy a pedir pescado.",
    translation: "I am going to order fish.",
    tip: "Pedir means to ask for/order.",
    category: "Restaurants",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "servir",
    english: "to serve",
    pos: "verb",
    example: "Sirven comida deliciosa.",
    translation: "They serve delicious food.",
    tip: "Servir is stem-changing.",
    category: "Restaurants",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "el menú",
    english: "menu",
    pos: "noun",
    example: "El menú tiene muchas opciones.",
    translation: "The menu has many options.",
    tip: "Menú has an accent.",
    category: "Restaurants",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "la cuenta",
    english: "bill/check",
    pos: "noun",
    example: "La cuenta, por favor.",
    translation: "The check, please.",
    tip: "Useful restaurant phrase.",
    category: "Restaurants",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "haz",
    english: "do / make",
    pos: "command",
    example: "Haz la tarea.",
    translation: "Do the homework.",
    tip: "Haz is the tú command of hacer.",
    category: "Commands",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "pon",
    english: "put",
    pos: "command",
    example: "Pon el libro en la mesa.",
    translation: "Put the book on the table.",
    tip: "Pon is the tú command of poner.",
    category: "Commands",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "sal",
    english: "leave / go out",
    pos: "command",
    example: "Sal de la clase después del timbre.",
    translation: "Leave class after the bell.",
    tip: "Sal is the tú command of salir.",
    category: "Commands",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "ven",
    english: "come",
    pos: "command",
    example: "Ven aquí, por favor.",
    translation: "Come here, please.",
    tip: "Ven is the tú command of venir.",
    category: "Commands",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "di",
    english: "say / tell",
    pos: "command",
    example: "Di la verdad.",
    translation: "Tell the truth.",
    tip: "Di is the tú command of decir.",
    category: "Commands",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "ten",
    english: "have",
    pos: "command",
    example: "Ten cuidado.",
    translation: "Be careful.",
    tip: "Ten is used in ten cuidado.",
    category: "Commands",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "sé",
    english: "be",
    pos: "command",
    example: "Sé amable.",
    translation: "Be kind.",
    tip: "Sé is the tú command of ser.",
    category: "Commands",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "ve",
    english: "go",
    pos: "command",
    example: "Ve a la oficina.",
    translation: "Go to the office.",
    tip: "Ve is the tú command of ir.",
    category: "Commands",
    level: "Senderos 2",
    dailyEligible: true
  },
  {
    spanish: "es importante que",
    english: "it is important that",
    pos: "phrase",
    example: "Es importante que estudies cada día.",
    translation: "It is important that you study every day.",
    tip: "This often triggers subjunctive.",
    category: "Subjunctive Triggers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "es necesario que",
    english: "it is necessary that",
    pos: "phrase",
    example: "Es necesario que llegues temprano.",
    translation: "It is necessary that you arrive early.",
    tip: "This often triggers subjunctive.",
    category: "Subjunctive Triggers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "dudo que",
    english: "I doubt that",
    pos: "phrase",
    example: "Dudo que él tenga razón.",
    translation: "I doubt that he is right.",
    tip: "Doubt often triggers subjunctive.",
    category: "Subjunctive Triggers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "ojalá que",
    english: "hopefully / I hope that",
    pos: "phrase",
    example: "Ojalá que tengamos tiempo.",
    translation: "Hopefully we have time.",
    tip: "Ojalá often uses subjunctive.",
    category: "Subjunctive Triggers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "recomiendo que",
    english: "I recommend that",
    pos: "phrase",
    example: "Recomiendo que practiques más.",
    translation: "I recommend that you practice more.",
    tip: "Recommendations often trigger subjunctive.",
    category: "Subjunctive Triggers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "es posible que",
    english: "it is possible that",
    pos: "phrase",
    example: "Es posible que llueva mañana.",
    translation: "It is possible that it will rain tomorrow.",
    tip: "Possibility can trigger subjunctive.",
    category: "Subjunctive Triggers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "no creo que",
    english: "I don’t think that",
    pos: "phrase",
    example: "No creo que sea fácil.",
    translation: "I do not think it is easy.",
    tip: "Negated belief often triggers subjunctive.",
    category: "Subjunctive Triggers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "antes de que",
    english: "before",
    pos: "phrase",
    example: "Estudia antes de que empiece la clase.",
    translation: "Study before class starts.",
    tip: "Antes de que often uses subjunctive.",
    category: "Subjunctive Triggers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "me alegra que",
    english: "I’m glad that",
    pos: "phrase",
    example: "Me alegra que estés aquí.",
    translation: "I’m glad that you are here.",
    tip: "Emotion often triggers subjunctive.",
    category: "Opinions & Emotions",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "me molesta que",
    english: "it bothers me that",
    pos: "phrase",
    example: "Me molesta que no escuches.",
    translation: "It bothers me that you do not listen.",
    tip: "Emotion/reaction often triggers subjunctive.",
    category: "Opinions & Emotions",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "opinar",
    english: "to think / to give an opinion",
    pos: "verb",
    example: "Quiero opinar sobre el tema.",
    translation: "I want to give an opinion about the topic.",
    tip: "Opinar is for opinions.",
    category: "Opinions & Emotions",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "estar de acuerdo",
    english: "to agree",
    pos: "phrase",
    example: "Estoy de acuerdo con tu idea.",
    translation: "I agree with your idea.",
    tip: "De acuerdo means in agreement.",
    category: "Opinions & Emotions",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "no estar de acuerdo",
    english: "to disagree",
    pos: "phrase",
    example: "No estoy de acuerdo con esa opinión.",
    translation: "I disagree with that opinion.",
    tip: "Useful debate phrase.",
    category: "Opinions & Emotions",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "preocupar",
    english: "to worry",
    pos: "verb",
    example: "El examen me preocupa.",
    translation: "The test worries me.",
    tip: "Preocupar works like gustar in this sentence.",
    category: "Opinions & Emotions",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "sentirse orgulloso",
    english: "to feel proud",
    pos: "phrase",
    example: "Me siento orgullosa de mi trabajo.",
    translation: "I feel proud of my work.",
    tip: "Orgulloso/a means proud.",
    category: "Opinions & Emotions",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "avergonzarse",
    english: "to be embarrassed",
    pos: "verb",
    example: "Me avergüenzo cuando cometo errores.",
    translation: "I get embarrassed when I make mistakes.",
    tip: "Reflexive emotion verb.",
    category: "Opinions & Emotions",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "el medio ambiente",
    english: "the environment",
    pos: "noun",
    example: "Debemos proteger el medio ambiente.",
    translation: "We should protect the environment.",
    tip: "Medio ambiente means environment.",
    category: "Environment",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "reciclar",
    english: "to recycle",
    pos: "verb",
    example: "Es importante reciclar plástico y papel.",
    translation: "It is important to recycle plastic and paper.",
    tip: "Reciclar looks like recycle.",
    category: "Environment",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "ahorrar energía",
    english: "to save energy",
    pos: "phrase",
    example: "Debemos ahorrar energía.",
    translation: "We should save energy.",
    tip: "Ahorrar means to save.",
    category: "Environment",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la contaminación",
    english: "pollution",
    pos: "noun",
    example: "La contaminación afecta la salud.",
    translation: "Pollution affects health.",
    tip: "Contaminación looks like contamination.",
    category: "Environment",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "el cambio climático",
    english: "climate change",
    pos: "noun",
    example: "El cambio climático es urgente.",
    translation: "Climate change is urgent.",
    tip: "Cambio means change.",
    category: "Environment",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "los recursos naturales",
    english: "natural resources",
    pos: "noun",
    example: "Debemos cuidar los recursos naturales.",
    translation: "We should care for natural resources.",
    tip: "Recursos means resources.",
    category: "Environment",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la sequía",
    english: "drought",
    pos: "noun",
    example: "La sequía afecta a los agricultores.",
    translation: "The drought affects farmers.",
    tip: "Sequía means drought.",
    category: "Environment",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "proteger",
    english: "to protect",
    pos: "verb",
    example: "Queremos proteger los bosques.",
    translation: "We want to protect forests.",
    tip: "Proteger means protect.",
    category: "Environment",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la pobreza",
    english: "poverty",
    pos: "noun",
    example: "La pobreza es un problema serio.",
    translation: "Poverty is a serious problem.",
    tip: "Pobre means poor; pobreza means poverty.",
    category: "Social Issues",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la desigualdad",
    english: "inequality",
    pos: "noun",
    example: "La desigualdad afecta muchas comunidades.",
    translation: "Inequality affects many communities.",
    tip: "Igualdad means equality; desigualdad means inequality.",
    category: "Social Issues",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "los derechos",
    english: "rights",
    pos: "noun",
    example: "Todos tienen derechos.",
    translation: "Everyone has rights.",
    tip: "Derechos means rights.",
    category: "Social Issues",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la comunidad",
    english: "community",
    pos: "noun",
    example: "La comunidad necesita apoyo.",
    translation: "The community needs support.",
    tip: "Comunidad looks like community.",
    category: "Social Issues",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la justicia",
    english: "justice",
    pos: "noun",
    example: "La justicia es importante para la sociedad.",
    translation: "Justice is important for society.",
    tip: "Justicia means justice.",
    category: "Social Issues",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la vivienda",
    english: "housing",
    pos: "noun",
    example: "La vivienda es muy cara en algunas ciudades.",
    translation: "Housing is very expensive in some cities.",
    tip: "Vivienda comes from vivir.",
    category: "Social Issues",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la educación",
    english: "education",
    pos: "noun",
    example: "La educación cambia oportunidades.",
    translation: "Education changes opportunities.",
    tip: "Educación means education.",
    category: "Social Issues",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "apoyar",
    english: "to support",
    pos: "verb",
    example: "Debemos apoyar a las familias.",
    translation: "We should support families.",
    tip: "Apoyar means support.",
    category: "Social Issues",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la identidad",
    english: "identity",
    pos: "noun",
    example: "La identidad cultural es importante.",
    translation: "Cultural identity is important.",
    tip: "Identidad looks like identity.",
    category: "Identity & Culture",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la herencia",
    english: "heritage",
    pos: "noun",
    example: "La herencia familiar influye en mi identidad.",
    translation: "Family heritage influences my identity.",
    tip: "Herencia can mean inheritance or heritage.",
    category: "Identity & Culture",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "las costumbres",
    english: "customs",
    pos: "noun",
    example: "Las costumbres varían entre culturas.",
    translation: "Customs vary between cultures.",
    tip: "Costumbres means customs/habits.",
    category: "Identity & Culture",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "pertenecer",
    english: "to belong",
    pos: "verb",
    example: "Quiero pertenecer a una comunidad.",
    translation: "I want to belong to a community.",
    tip: "Pertenecer means to belong.",
    category: "Identity & Culture",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la tradición",
    english: "tradition",
    pos: "noun",
    example: "La tradición une a la familia.",
    translation: "Tradition unites the family.",
    tip: "Tradición means tradition.",
    category: "Identity & Culture",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la generación",
    english: "generation",
    pos: "noun",
    example: "Cada generación tiene experiencias diferentes.",
    translation: "Each generation has different experiences.",
    tip: "Generación means generation.",
    category: "Identity & Culture",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la lengua materna",
    english: "native language",
    pos: "noun",
    example: "El árabe es su lengua materna.",
    translation: "Arabic is her native language.",
    tip: "Lengua materna means native language.",
    category: "Identity & Culture",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "adaptarse",
    english: "to adapt",
    pos: "verb",
    example: "Es difícil adaptarse a una cultura nueva.",
    translation: "It is difficult to adapt to a new culture.",
    tip: "Adaptarse is reflexive.",
    category: "Identity & Culture",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "las redes sociales",
    english: "social media",
    pos: "noun",
    example: "Las redes sociales influyen en los jóvenes.",
    translation: "Social media influences young people.",
    tip: "Redes means networks.",
    category: "Technology & Media",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la pantalla",
    english: "screen",
    pos: "noun",
    example: "Paso mucho tiempo frente a la pantalla.",
    translation: "I spend a lot of time in front of the screen.",
    tip: "Pantalla means screen.",
    category: "Technology & Media",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la privacidad",
    english: "privacy",
    pos: "noun",
    example: "La privacidad en internet es importante.",
    translation: "Privacy on the internet is important.",
    tip: "Privacidad looks like privacy.",
    category: "Technology & Media",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "compartir",
    english: "to share",
    pos: "verb",
    example: "No debes compartir información privada.",
    translation: "You should not share private information.",
    tip: "Compartir means to share.",
    category: "Technology & Media",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la contraseña",
    english: "password",
    pos: "noun",
    example: "No compartas tu contraseña.",
    translation: "Do not share your password.",
    tip: "Contraseña means password.",
    category: "Technology & Media",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la noticia",
    english: "news item",
    pos: "noun",
    example: "Leí una noticia interesante.",
    translation: "I read an interesting news story.",
    tip: "Noticia means news item.",
    category: "Technology & Media",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "el anuncio",
    english: "advertisement / announcement",
    pos: "noun",
    example: "El anuncio intenta persuadirnos.",
    translation: "The advertisement tries to persuade us.",
    tip: "Anuncio can be ad/announcement.",
    category: "Technology & Media",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "publicar",
    english: "to publish/post",
    pos: "verb",
    example: "Voy a publicar un video educativo.",
    translation: "I am going to post an educational video.",
    tip: "Publicar means publish/post.",
    category: "Technology & Media",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la meta",
    english: "goal",
    pos: "noun",
    example: "Mi meta es hablar con fluidez.",
    translation: "My goal is to speak fluently.",
    tip: "Meta means goal.",
    category: "Future & Goals",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "lograr",
    english: "to achieve",
    pos: "verb",
    example: "Quiero lograr mis metas.",
    translation: "I want to achieve my goals.",
    tip: "Lograr means to achieve.",
    category: "Future & Goals",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "desarrollar",
    english: "to develop",
    pos: "verb",
    example: "Quiero desarrollar mejores hábitos.",
    translation: "I want to develop better habits.",
    tip: "Desarrollar means to develop.",
    category: "Future & Goals",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "el futuro",
    english: "future",
    pos: "noun",
    example: "Pienso mucho en el futuro.",
    translation: "I think a lot about the future.",
    tip: "Futuro means future.",
    category: "Future & Goals",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "alcanzar",
    english: "to reach / achieve",
    pos: "verb",
    example: "Quiero alcanzar mis objetivos.",
    translation: "I want to reach my goals.",
    tip: "Alcanzar means reach/achieve.",
    category: "Future & Goals",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "el propósito",
    english: "purpose",
    pos: "noun",
    example: "El proyecto tiene un propósito claro.",
    translation: "The project has a clear purpose.",
    tip: "Propósito means purpose.",
    category: "Future & Goals",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la disciplina",
    english: "discipline",
    pos: "noun",
    example: "La disciplina ayuda con las metas.",
    translation: "Discipline helps with goals.",
    tip: "Disciplina means discipline.",
    category: "Future & Goals",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la confianza",
    english: "confidence / trust",
    pos: "noun",
    example: "La práctica aumenta la confianza.",
    translation: "Practice increases confidence.",
    tip: "Confianza can mean confidence or trust.",
    category: "Future & Goals",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la carrera",
    english: "career / major",
    pos: "noun",
    example: "Quiero una carrera en psicología.",
    translation: "I want a career in psychology.",
    tip: "Carrera can mean career, race, or major.",
    category: "Careers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "el empleo",
    english: "job / employment",
    pos: "noun",
    example: "Busco un empleo de verano.",
    translation: "I am looking for a summer job.",
    tip: "Empleo means employment/job.",
    category: "Careers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la entrevista",
    english: "interview",
    pos: "noun",
    example: "Tengo una entrevista mañana.",
    translation: "I have an interview tomorrow.",
    tip: "Entrevista means interview.",
    category: "Careers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "solicitar",
    english: "to apply for",
    pos: "verb",
    example: "Voy a solicitar una beca.",
    translation: "I am going to apply for a scholarship.",
    tip: "Solicitar means to request/apply for.",
    category: "Careers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "la beca",
    english: "scholarship",
    pos: "noun",
    example: "Recibió una beca para estudiar.",
    translation: "She received a scholarship to study.",
    tip: "Beca means scholarship.",
    category: "Careers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "el currículum",
    english: "résumé",
    pos: "noun",
    example: "Necesito preparar mi currículum.",
    translation: "I need to prepare my résumé.",
    tip: "Currículum means résumé/CV.",
    category: "Careers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "el voluntariado",
    english: "volunteering",
    pos: "noun",
    example: "El voluntariado ayuda a la comunidad.",
    translation: "Volunteering helps the community.",
    tip: "Voluntariado means volunteer work.",
    category: "Careers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "el liderazgo",
    english: "leadership",
    pos: "noun",
    example: "El club enseña liderazgo.",
    translation: "The club teaches leadership.",
    tip: "Liderazgo means leadership.",
    category: "Careers",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "aunque",
    english: "although / even if",
    pos: "conjunction",
    example: "Aunque sea difícil, voy a practicar.",
    translation: "Although it is difficult, I am going to practice.",
    tip: "Aunque is useful for complex sentences.",
    category: "Advanced Connectors",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "sin embargo",
    english: "however",
    pos: "connector",
    example: "El examen fue difícil; sin embargo, aprobé.",
    translation: "The test was difficult; however, I passed.",
    tip: "Sin embargo is a strong transition.",
    category: "Advanced Connectors",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "por lo tanto",
    english: "therefore",
    pos: "connector",
    example: "Estudié mucho; por lo tanto, estaba preparada.",
    translation: "I studied a lot; therefore, I was prepared.",
    tip: "Use it for cause/effect.",
    category: "Advanced Connectors",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "a pesar de",
    english: "despite",
    pos: "phrase",
    example: "A pesar de la lluvia, salimos.",
    translation: "Despite the rain, we went out.",
    tip: "A pesar de shows contrast.",
    category: "Advanced Connectors",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "por otro lado",
    english: "on the other hand",
    pos: "connector",
    example: "Por otro lado, la tecnología puede distraer.",
    translation: "On the other hand, technology can distract.",
    tip: "Useful for balanced arguments.",
    category: "Advanced Connectors",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "además",
    english: "furthermore / besides",
    pos: "connector",
    example: "Además, necesitamos más tiempo.",
    translation: "Furthermore, we need more time.",
    tip: "Adds another point.",
    category: "Advanced Connectors",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "en cambio",
    english: "instead / in contrast",
    pos: "connector",
    example: "Yo prefiero leer; en cambio, él prefiere correr.",
    translation: "I prefer reading; in contrast, he prefers running.",
    tip: "Shows contrast.",
    category: "Advanced Connectors",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "debido a",
    english: "due to",
    pos: "phrase",
    example: "Debido a la lluvia, cancelaron el partido.",
    translation: "Due to the rain, they canceled the game.",
    tip: "Formal cause phrase.",
    category: "Advanced Connectors",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "he aprendido",
    english: "I have learned",
    pos: "verb",
    example: "He aprendido muchas palabras nuevas.",
    translation: "I have learned many new words.",
    tip: "Present perfect uses haber + past participle.",
    category: "Present Perfect",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "has visto",
    english: "you have seen",
    pos: "verb",
    example: "¿Has visto esta película?",
    translation: "Have you seen this movie?",
    tip: "Has is the tú form of haber.",
    category: "Present Perfect",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "ha cambiado",
    english: "has changed",
    pos: "verb",
    example: "La sociedad ha cambiado mucho.",
    translation: "Society has changed a lot.",
    tip: "Ha + participle.",
    category: "Present Perfect",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "hemos estudiado",
    english: "we have studied",
    pos: "verb",
    example: "Hemos estudiado por dos horas.",
    translation: "We have studied for two hours.",
    tip: "Hemos is nosotros form of haber.",
    category: "Present Perfect",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "han dicho",
    english: "they have said",
    pos: "verb",
    example: "Han dicho la verdad.",
    translation: "They have told the truth.",
    tip: "Dicho is irregular past participle.",
    category: "Present Perfect",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "he hecho",
    english: "I have done/made",
    pos: "verb",
    example: "He hecho mi tarea.",
    translation: "I have done my homework.",
    tip: "Hecho is irregular past participle.",
    category: "Present Perfect",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "ha abierto",
    english: "has opened",
    pos: "verb",
    example: "La escuela ha abierto temprano.",
    translation: "The school has opened early.",
    tip: "Abierto is irregular past participle.",
    category: "Present Perfect",
    level: "Senderos 3",
    dailyEligible: true
  },
  {
    spanish: "hemos escrito",
    english: "we have written",
    pos: "verb",
    example: "Hemos escrito un ensayo.",
    translation: "We have written an essay.",
    tip: "Escrito is irregular past participle.",
    category: "Present Perfect",
    level: "Senderos 3",
    dailyEligible: true
  },
];
